# trunk-ignore-all(checkov/CKV2_GHA_1)
name: My First GitHub Action
on: [push]
jobs: # the jobs don't run in sequence , the steps do (-)
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Setup Finish
        run: echo "Setup Finish"
        # if we want 2nd job and pass data from 1st job to 2nd job
  test-app:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Test the project
        run: npm run test
      - name: Test Finish
        run: echo "Test Finish"
