# trunk-ignore-all(checkov/CKV2_GHA_1)
name: My First GitHub Action
on: [push]
jobs: # the jobs don't run in sequence , the steps do (-)
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Worldddd....."
      - run: echo "This is step number 2"
