# trunk-ignore-all(checkov/CKV2_GHA_1)
name: My First GitHub Action
on: [push]
jobs: # the jobs don't run in sequence , the steps do (-)
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
